server.port=8080

# Application Name
spring.application.name=employee-registration

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/caru4u
spring.datasource.username=postgres
spring.datasource.password=Darshan@8548
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=caru4uadmin@gmail.com
spring.mail.password=xlzh tgbo xpdw foln

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


twilio.accountSid=ACe2a002534332506180bb60ac0c8bf749
#VA3f463b742ca66b24f09643d3db4fcc57
twilio.authToken=833c924472c0e922448e68efc576e9d7
twilio.fromNumber=+919035803009
otp.expiry.seconds=300
