server.port=8080

# Application Name
spring.application.name=employee-registration

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/caru4u
spring.datasource.username=postgres
spring.datasource.password=Darshan@8548
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect