# Server Port
server.port=8080

# Application Name
spring.application.name=employee-registration

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/caru4u
spring.datasource.username=postgres
spring.datasource.password=Darshan@8548
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=22MB

server.error.include-message=always
server.error.include-binding-errors=always

